/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/**
 * Generates the landing page in every language, and the sitemap.
 *
 * Output: docs/index.html (English, the default), docs/<path>/index.html for
 * each other language, docs/sitemap.xml. Plain static HTML — no script runs on
 * the site, no redirect, no detection. Run through tools/build-pages.sh.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const DOCS = path.resolve(__dirname, '..', '..', 'docs');
const SITE = 'https://mars073.github.io/Preply-canvas-archiver/';
const REPO = 'https://github.com/Mars073/Preply-canvas-archiver';

const STORE = {
  chrome: 'https://chromewebstore.google.com/detail/preply-canvas-archiver/clhcjjambcaodbnaenpimnbedlhohmdj',
  firefox: 'https://addons.mozilla.org/firefox/addon/preply-canvas-archiver/',
  edge: 'https://microsoftedge.microsoft.com/addons/detail/preply-canvas-archiver/ocbalfmganjedonhaekgbpkiljhiongf',
};

/** Page order in the language menu and in every hreflang block. English first: it is x-default. */
const PAGES = ['en', 'fr', 'es', 'pl', 'ru', 'zh'].map((id) => require(`./${id}.js`));

const HEADER = `<!-- This Source Code Form is subject to the terms of the Mozilla Public
     License, v. 2.0. If a copy of the MPL was not distributed with this
     file, You can obtain one at https://mozilla.org/MPL/2.0/.

     Generated by tools/build-pages.sh from tools/pages/. Do not edit. -->`;

const CSS = fs.readFileSync(path.join(__dirname, 'style.css'), 'utf8')
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .replace(/\n\s*\n+/g, '\n')
  .trim();

/**
 * @param {string} s
 * @returns {string} safe inside an attribute value or text.
 */
function attr(s) {
  return s.replace(/&(?![a-z#0-9]+;)/gi, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
}

/**
 * @param {string} html - a translated fragment.
 * @returns {string} its plain text, for structured data.
 */
function plain(html) {
  return html
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&#8239;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * @param {object} page
 * @returns {string} absolute URL of the page.
 */
function urlOf(page) {
  return SITE + page.path;
}

/**
 * @param {object} from
 * @param {object} to
 * @returns {string} relative link between two pages, so the site also works opened from disk.
 */
function link(from, to) {
  if (from.path === '') return to.path || './';
  return '../' + to.path;
}

/**
 * Fails the build when a translation is missing a field the English page has.
 *
 * @param {unknown} ref - the English value.
 * @param {unknown} got - the translated value.
 * @param {string} where
 * @returns {void}
 * @throws {Error} when a key is missing, has another type, or an array is empty.
 */
function assertShape(ref, got, where) {
  if (Array.isArray(ref)) {
    if (!Array.isArray(got) || got.length === 0) throw new Error(`${where}: expected a non-empty array`);
    got.forEach((item, i) => assertShape(ref[0], item, `${where}[${i}]`));
    return;
  }
  if (ref && typeof ref === 'object') {
    if (!got || typeof got !== 'object') throw new Error(`${where}: expected an object`);
    for (const key of Object.keys(ref)) assertShape(ref[key], got[key], `${where}.${key}`);
    return;
  }
  if (typeof got !== typeof ref || got === '') throw new Error(`${where}: missing or empty`);
}

/**
 * @param {object} t - one language module.
 * @returns {string} the whole page.
 */
function render(t) {
  const base = t.path ? '../' : '';
  const url = urlOf(t);

  const alternates = PAGES
    .map((p) => `<link rel="alternate" hreflang="${p.hreflang}" href="${urlOf(p)}">`)
    .concat(`<link rel="alternate" hreflang="x-default" href="${urlOf(PAGES[0])}">`)
    .join('\n');

  const locales = PAGES
    .filter((p) => p !== t)
    .map((p) => `<meta property="og:locale:alternate" content="${p.ogLocale}">`)
    .join('\n');

  const menu = PAGES
    .map((p) => `<a href="${link(t, p)}" hreflang="${p.hreflang}" lang="${p.hreflang}"`
      + (p === t ? ' aria-current="page"' : '') + `>${p.label}</a>`)
    .join('\n      ');

  const ld = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'SoftwareApplication',
        name: 'Preply Canvas Archiver',
        applicationCategory: 'BrowserApplication',
        operatingSystem: 'Firefox, Chrome, Edge',
        description: t.ldDescription,
        url,
        codeRepository: REPO,
        license: 'https://www.mozilla.org/MPL/2.0/',
        isAccessibleForFree: true,
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' },
        inLanguage: PAGES.map((p) => p.hreflang),
      },
      {
        '@type': 'FAQPage',
        inLanguage: t.hreflang,
        mainEntity: t.faq.items.map((q) => ({
          '@type': 'Question',
          name: plain(q.q),
          acceptedAnswer: { '@type': 'Answer', text: plain(q.a) },
        })),
      },
    ],
  };
  const json = JSON.stringify(ld, null, 2).replace(/</g, '\\u003c');

  const pairs = t.hard.items
    .map((i) => `        <div>
          <h3>${i.h3}</h3>
          <p>${i.p}</p>
        </div>`)
    .join('\n');

  const faq = t.faq.items
    .map((i) => `        <h3>${i.q}</h3>
        <p>${i.a}</p>`)
    .join('\n');

  return `<!doctype html>
${HEADER}
<html lang="${t.hreflang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${t.title}</title>
<meta name="description" content="${attr(t.description)}">
<link rel="canonical" href="${url}">
${alternates}
<link rel="icon" type="image/svg+xml" href="${base}logo.svg">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Preply Canvas Archiver">
<meta property="og:locale" content="${t.ogLocale}">
${locales}
<meta property="og:title" content="${attr(t.ogTitle)}">
<meta property="og:description" content="${attr(t.ogDescription)}">
<meta property="og:url" content="${url}">
<meta property="og:image" content="${SITE}og-image.png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="${attr(t.ogImageAlt)}">
<meta name="twitter:card" content="summary_large_image">
<script type="application/ld+json">
${json}
</script>
<style>
${CSS}
</style>
</head>
<body>

<a class="skip" href="#content">${t.skip}</a>

<div class="w">
  <header class="top">
    <img src="${base}logo.svg" alt="">
    <b>Preply Canvas Archiver</b>
    <nav aria-label="${attr(t.navLabel)}">
      ${menu}
    </nav>
  </header>
</div>

<main id="content">
  <div class="w">

    <h1>${t.h1}</h1>
    <p class="sub">${t.sub}</p>
    <div class="actions">
      <a class="glossy" href="${STORE.chrome}">
        <img src="${base}icons/chrome.svg" width="32" height="32" alt="" aria-hidden="true">
        ${t.addChrome}
      </a>
      <a class="alpenglow" href="${STORE.firefox}">
        <span class="face">
          <img src="${base}icons/firefox.svg" width="32" height="32" alt="" aria-hidden="true">
          ${t.addFirefox}
        </span>
      </a>
      <a class="edge" href="${STORE.edge}">
        <img src="${base}icons/edge.svg" width="32" height="32" alt="" aria-hidden="true">
        ${t.addEdge}
      </a>
    </div>

    <div class="shot">
      <img src="${base}screenshots/archive-viewer.png" width="1916" height="1048" decoding="async"
           alt="${attr(t.shotAlt)}">
    </div>
    <p class="cap">${t.shotCap}</p>

    <section>
      <h2>${t.how.h2}</h2>
      <p>${t.how.p}</p>
      <div class="shot" style="margin-top:32px">
        <img src="${base}screenshots/toolbar-button.png" width="1461" height="772" loading="lazy" decoding="async"
             alt="${attr(t.how.shotAlt)}">
      </div>
      <p class="cap">${t.how.cap}</p>
    </section>

    <section>
      <h2>${t.read.h2}</h2>
      <p>${t.read.p1}</p>
      <p>${t.read.p2}</p>
    </section>

    <section>
      <h2>${t.privacy.h2}</h2>
      <p>${t.privacy.p1}</p>
      <p>${t.privacy.p2}</p>
    </section>

    <section id="faq">
      <h2>${t.faq.h2}</h2>
      <div class="faq">
${faq}
      </div>
    </section>

    <section>
      <h2>${t.hard.h2}</h2>
      <div class="pair">
${pairs}
      </div>
    </section>

    <section>
      <h2>${t.source.h2}</h2>
      <p>${t.source.intro}</p>
      <dl class="steps">
        <dt>Firefox</dt>
        <dd>${t.source.firefox}</dd>
        <dt>${t.source.chromeTitle}</dt>
        <dd>${t.source.chrome}</dd>
      </dl>
      <p style="margin-top:20px">${t.source.noBuild}</p>
      <p>${t.source.past}</p>
    </section>

    <section>
      <h2>${t.thanks.h2}</h2>
      <p>${t.thanks.p}</p>
    </section>

  </div>
</main>

<footer>
  <div class="w">
    <p><a href="${REPO}">${t.footer.source}</a> ·
       <a href="${REPO}/blob/master/LICENSE">MPL&nbsp;2.0</a> ·
       <a href="${REPO}/blob/master/PRIVACY.md">${t.footer.privacy}</a> ·
       ${t.footer.icons}</p>
    <p>${t.footer.disclaimer}</p>
  </div>
</footer>

</body>
</html>
`;
}

/** @returns {string} the sitemap, every page listing every alternate. */
function sitemap() {
  const alternates = PAGES
    .map((p) => `    <xhtml:link rel="alternate" hreflang="${p.hreflang}" href="${urlOf(p)}"/>`)
    .concat(`    <xhtml:link rel="alternate" hreflang="x-default" href="${urlOf(PAGES[0])}"/>`)
    .join('\n');
  const urls = PAGES
    .map((p) => `  <url>\n    <loc>${urlOf(p)}</loc>\n${alternates}\n  </url>`)
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${urls}
</urlset>
`;
}

for (const page of PAGES.slice(1)) assertShape(PAGES[0], page, page.hreflang);

for (const page of PAGES) {
  const dir = path.join(DOCS, page.path);
  fs.mkdirSync(dir, { recursive: true });
  const html = render(page);
  fs.writeFileSync(path.join(dir, 'index.html'), html);
  console.log(`${(page.path || '/').padEnd(5)} ${page.hreflang.padEnd(8)} ${String(html.length).padStart(6)} B  ${plain(page.title).length} title / ${plain(page.description).length} description chars`);
}
fs.writeFileSync(path.join(DOCS, 'sitemap.xml'), sitemap());
console.log(`sitemap.xml  ${PAGES.length} URLs`);
